APP_NAME = 'GeoTrace Forensics X'
APP_VERSION = '12.9.2'
APP_ORGANIZATION = 'Cyber Forensics Team'
APP_BUILD_CHANNEL = 'Public Release Candidate'
APP_RELEASE_FLAVOR = 'AI Guardian v5 / Deep Context Reasoner'
APP_COPYRIGHT = 'GeoTrace Forensics X • AI-Assisted Investigation Build • OSINT CTF GeoLocator Build'
DEFAULT_ANALYST_NAME = 'Lead Analyst'
